### ISSUE TITLE
New build infrastructure for coqorg/org:dev with metadata labels, badges, and SHA1 pinning

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq#1]
### Summary

I refactored the docker-coq build setup of the `coqorg/coq:dev` image so the underlying SHA1 of the `coq.dev` opam package is exposed as a Docker `LABEL`, and as a Markdown badge in <https://hub.docker.com/r/coqorg/coq>.

This new setup relies on the [`hooks/build` "advanced feature" of Docker Hub](https://docs.docker.com/docker-hub/builds/advanced/) and generates some metadata labels using the [label-schema.org convention](https://microbadger.com/labels).

As an aside, this new infrastructure fixes the following rare but nasty bug: as `coq.dev` is installed in two opam switches, it could have been possible to obtain a different version of Coq between both opam switches… (if a PR had been merged before these two steps of the nightly build!)

Now, the version consistency between the two SHA1's is guaranteed thanks to a prior HTTP request to the corresponding GitHub API.

I'll close this issue once the build of the corresponding images (currently queued on Docker Hub) will be finished.

**Comment by ejgallego** [comment]
Very nice, now the build list displays the commit source!

**Comment by erikmd** [comment]
Yes, and to be more precise:

* The commit source mentioned in https://hub.docker.com/r/coqorg/coq/builds refers to the commit hash for this "Dockerfile repo"
* The commit badge mentioned in https://hub.docker.com/r/coqorg/coq/ refers to the commit hash for the Coq version packaged in `coqorg/coq:dev`

**Comment by erikmd** [comment]
As you suggested I bumped the edge+flambda version of OCaml:
https://github.com/coq-community/docker-base/commit/37071d986558df488d681e9e1c8afb7a9e8739d9
But I guess we'll have to wait for ~12h so every image is rebuilt.
(I especially faced a bug that slowed down these builds, it has been reported in docker/hub-feedback#1784)

**Comment by erikmd** [comment]
The update of images is done: with OPAM 2.0.4 and `COMPILER_EDGE=4.07.1+flambda` (for Coq≥8.7),
cf. https://hub.docker.com/r/coqorg/coq/; this page also contains a badge to help browsing the metadata of the `coqorg/coq:dev` image, linking to https://microbadger.com/images/coqorg/coq:dev
