### ISSUE TITLE
Document which opam repositories are available in Docker images

### ISSUE THREAD

**Issue by anton-trunov** [coq-community/docker-coq#25]
Hi @erikmd!

There are three standard Coq opam repositories:

- https://coq.inria.fr/opam/released
- https://coq.inria.fr/opam/core-dev
- https://coq.inria.fr/opam/extra-dev

Is it easy to find out which ones are available in each Docker image (or a family of images) or should we try documenting it in the wiki? Thank you.

**Comment by Blaisorblade** [comment]
Docs are missing but `opam repo list` can say (and is more up-to-date than a copy in the docs). Only coq-released seems available by default:

https://gitlab.com/coq-community/docker-base/-/blob/master/base/single/Dockerfile 
https://gitlab.com/coq-community/docker-base/-/blob/master/base/dual/Dockerfile

We could keep the issue open but you should just feel free to edit the wiki if you'd like... So in doubt, I'll tentatively close this.
