### ISSUE TITLE
Which default OCaml version for the images

### ISSUE THREAD

**Issue by clarus** [coq-community/docker-coq#30]
This is slightly related to https://github.com/coq-community/docker-coq/issues/12 ,  but I wonder which default OCaml version should be in the Docker images. Someone posted me a bug https://github.com/coq-io/system-ocaml/issues/5 related to the image `coqorg/coq:8.13.2`, where only OCaml 4.05 and 4.07 are available. His example was working with more recent OCaml versions. 

So I wonder if we should have a more recent default OCaml version, like 4.11 or 4.12 by default (the `4.07.1` being almost three years old for example, and incompatible with the latest Dune versions without using `ocaml-secondary-compiler` which is basically installing a second OCaml compiler).

**Comment by erikmd** [comment]
Hi @clarus,
Sorry for not replying earlier; but FYI all docker-coq images have just been rebuilt and the coq/ocaml mapping simplified/updated → All this is documented in this wiki page:
https://github.com/coq-community/docker-coq/wiki#ocaml-versions-policy

So I believe this issue can be closed.
Cheers,
E.
