### ISSUE TITLE
Integrate dune 3.8.1 as soon as possible

### ISSUE THREAD

**Issue by erikmd** [coq-community/docker-coq#56]
Namely, when `dune.3.8.0` goes live in opam: https://opam.ocaml.org/packages/dune/

Related: https://github.com/ocaml/opam-repository/pull/23814
& https://coq.zulipchat.com/#narrow/stream/237663-coq-community-devs-.26-users/topic/Dune.203.2E8.20with.20Coq.20composition.20in.20CI/near/361264335

**Comment by erikmd** [comment]
Hi @Alizter, OK thanks!

> Dune crashes when looking for COQ_NATIVE_COMPILER_DEFAULT when it is missing in Coq < 8.13.

Does this mean that `dune.3.8.0` is incompatible with 8.4 ≤ Coq ≤ 8.12 ?

In which case, I'm afraid we cannot do the bump now, given `dune` is installed in the same *base* image used for any Coq version, only specialized w.r.t. the Coq version.

**Comment by erikmd** [comment]
@Alizter
> COQPATHs with overlapping theory prefixes
can you be more specific? you mean coq packages that install to the same folder `…/user-contrib/mathcomp/`?

anyway, could you link to the issue(s) on this bug if there are already some?

**Comment by Alizter** [comment]
For the native compiler issue we have https://github.com/ocaml/dune/issues/7846. This will only be triggered when the coq.theory stanza does not have a mode set. There will be a fix for this in 3.8.1. https://github.com/ocaml/dune/pull/7847

The COQPATH issue is as you describe. However this only affects how we package things in nix. When you have say mathcomp/ssreflect and mathcomp/algebra installed in user-contrib (as opam will do) this is not a problem. However when we look for directories in COQPATH, dune will currently think there are two conflicting theories named mathcomp. This is a bug and I hope to fix it for 3.8.1 as well, but it shouldn't be a problem for the platform. https://github.com/ocaml/dune/pull/7790

**Comment by erikmd** [comment]
OK! so I'd say, let's wait for 3.8.1 :+1:

**Comment by Alizter** [comment]
@erikmd 3.8.1 has been released and is in opam. There are a few more bugs to fix for 3.8.2 but they shouldn't affect anything here.

**Comment by erikmd** [comment]
@Alizter thanks a lot for your heads-up and your reactivity!

**Comment by erikmd** [comment]
FYI: the [first `coqorg/base` pipeline](https://gitlab.com/coq-community/docker-base/-/pipelines/893177493) is on-going; stay tuned.

**Comment by erikmd** [comment]
FYI: the [second `coqorg/coq` pipeline](https://gitlab.com/coq-community/docker-coq/-/pipelines/893187263) is on-going; stay tuned.

**Comment by erikmd** [comment]
After necessary tweaks by @Zimmi48 in coqbot to workaround random failures at `docker pull` time in gitlab.inria.fr,
the [third `mathcomp/mathcomp` pipeline](https://gitlab.inria.fr/math-comp/docker-mathcomp/-/pipelines/819087) went fine.

And I updated the list of supported tags accordingly
https://hub.docker.com/r/mathcomp/mathcomp#supported-tags
— Thanks @proux01 for raising that documentation issue; I've just added a comment in [the mathcomp wiki](https://github.com/math-comp/math-comp/wiki/Howto-Release).

So now, this issue can be closed.

Thank you all @proux01 @Zimmi48 @Alizter !
